### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by mmower** [clojure-expectations/lein-autoexpect#17]
Hi.

I'm using lein-autoexpect with a Compojure+Liberator project and I'm finding that, quite frequently, it is throwing a rather baffling exception - apparently unrelated to my tests - that disappears as soon as I restart lein autoexpect (i.e. with no further changes to the tests or code under test).

Here's an example run where I correct three expected missing symbols (as I add those functions) at the fourth go the tests should be green:

```
Alia-2:sortapi matt$ lein autoexpect

*********************************************
*************** Running tests ***************

failure in (slist.clj:15) : sortapi.test.models.slist
(expect "test-1" (:name lst))

           expected: "test-1"
                was: nil

Ran 44 tests containing 44 assertions in 56 msecs
1 failures, 0 errors.
Tests completed at 13:58:36.495

*********************************************
*************** Running tests ***************
Error refreshing environment: java.lang.RuntimeException: Unable to resolve symbol: slist-name in this context, compiling:(sortapi/test/models/slist.clj:15:20)
Tests completed at 13:59:43.879

*********************************************
*************** Running tests ***************
Error refreshing environment: java.lang.RuntimeException: Unable to resolve symbol: slist-question in this context, compiling:(sortapi/test/models/slist.clj:16:30)
Tests completed at 13:59:59.849

*********************************************
*************** Running tests ***************
Error refreshing environment: java.lang.RuntimeException: Unable to resolve symbol: slist-email in this context, compiling:(sortapi/test/models/slist.clj:17:26)
Tests completed at 14:00:10.872

*********************************************
*************** Running tests ***************
Error refreshing environment: java.lang.Exception: namespace 'sortapi.handler' not found, compiling:(sortapi/test/handler.clj:1:1)
Tests completed at 14:00:20.932
^CAlia-2:sortapi matt$ lein autoexpect

*********************************************
*************** Running tests ***************

Ran 46 tests containing 46 assertions in 24 msecs
0 failures, 0 errors.
Tests completed at 14:00:39.474
```

The exception 'sortapi.handler' not found is the strange exception since the namespace is quite clearly there as the other tests wouldn't run without it and, of course, restarting autoexpect it finds it again.

I'm sure it's something I am doing but do you have any ideas where I could begin to look?

Best,

Matt

**Comment by mmower** [comment]
btw my twitter handle is @sandbags, happy to try and diagnose together if that's helpful.

**Comment by jakemcc** [comment]
Hmm, that is weird.

First thing I'd look at is that my `ns` forms are correct (using `:require` not `require`) as I've seen problems show up with tools.namespace that don't show up with other usage with `ns` forms that work in other scenarios.

Next I'd take a look at the `tools.namespace` [warnings](https://github.com/clojure/tools.namespace#warnings-and-potential-problems) (which, includes the above warning) and see if anything in there jumps out as a potential problem. One problem it points out is conflicting versions of `tools.namespace`. That is something I've seen cause problems in the past and either setting an explicit version or excluding other dependencies.

Doing anything advanced in your project.clj or profiles.clj?

What version of lein-autoexpect? The latest release recently upgraded the `tools.namespace` dependency. Might be worth trying it out if you are on an older version.

**Comment by mmower** [comment]
Hi Jake. I've added you as a collaborator to the project 'sortapi' so you can take a look at the project.clj and see if there's anything amiss either there or in my tests.

**Comment by mmower** [comment]
Are you on IRC?

**Comment by mmower** [comment]
I'm using [lein-autoexpect "1.4.2"]

**Comment by mmower** [comment]
All my (ns ...) declarations are using (:require) or (:use) and not (require) or (use).

**Comment by jakemcc** [comment]
@mmower I'm not on IRC. I'll try poking around after work and see if anything stands out.

How frequently does this happen? Happen often enough where reproducing it happens fairly quick?

**Comment by mmower** [comment]
Hi Jake. I'm self@mattmower.com on gchat if you use that?

It didn't happen at all, then it started to happen occasionally. What prompted me to write was it happening reliably enough to get really annoying with having to stop/start autoexpect so, yes, I think should be easy enough to reproduce.

m/

**Comment by jakemcc** [comment]
@mmower Still seeing the problem? Did the release that stopped suppressing stdout during reloads help with diagnosing?

I tried for a while to get the problem to repeat locally and wasn't able to.

**Comment by jakemcc** [comment]
Still having problems or did the change to no longer squash output while reloading help diagnose?

**Comment by emrehan** [comment]
I'm having the same exception:

```

*********************************************
*************** Running tests ***************
:reloading (spock.util.config spock.fs.ufs spock.predictor spock.clusterer spock.trainer spock.rest spock.core spock.rest-test spock.util.config-test)
Reflection warning, expectations.clj:88:16 - reference to field getStackTrace can't be resolved.
Reflection warning, expectations.clj:89:10 - reference to field getFileName on java.lang.Object can't be resolved.
Reflection warning, expectations.clj:89:31 - reference to field getLineNumber on java.lang.Object can't be resolved.
Reflection warning, expectations.clj:136:61 - reference to field getStackTrace can't be resolved.
Reflection warning, expectations.clj:185:71 - reference to field getMessage can't be resolved.
Reflection warning, expectations.clj:205:58 - reference to field name can't be resolved.
Reflection warning, expectations.clj:449:17 - reference to field pattern can't be resolved.
Reflection warning, expectations.clj:449:30 - reference to field pattern can't be resolved.
Reflection warning, expectations.clj:558:16 - reference to field ns can't be resolved.
Reflection warning, expectations.clj:558:28 - reference to field sym can't be resolved.
:error-while-loading spock.rest-test
Error refreshing environment: java.lang.Exception: namespace 'spock.rest' not found, compiling:(spock/rest_test.clj:1:1)
Tests completed at 10:46:20.524
```

It happens quite frequently when I change a different file than rest_test. I've tried using :use and :require and :reload-all flag but they didn't help.

**Comment by jakemcc** [comment]
@emrehan What version of lein-autoexpect are you using? If you aren't on the latest could you upgrade to `[lein-autoexpect "1.6.0"]` and see if that helps at all.

Another thing worth trying is to see if there is a `org.clojure/tools.namespace` dependency that is already getting pulled into the project. lein-autoexpect adds the version it depends on only if there isn't already the dependency. I've seen problems with old versions of tools.namespace in the past that have been solved by explicitly adding a dependency on the latest tools.namespace (`[org.clojure/tools.namespace "0.2.11"]`). I'd also look into doing this with an empty profiles.clj to minimize potential moving parts.

I still haven't been able to reproduce the earlier problem locally. Unfortunately these problems can be a bit hard to diagnose. You may need to clone lein-autoexpect and tools.namespace, add some debugging printlns and see if you can figure it out.



@mmower Still having problems? If not, any idea what changed?
